language: python
branches:
  only:
    - master
    - python3
python:
  - "2.7"
  - "3.3"
mysql:
  adapter: mysql2
  database: domogik
  username: travis
  encoding: utf8
install:
  - $TRAVIS_BUILD_DIR/src/domogik/tests/travis/travis-install-dependencies.sh
before_script:
  - $TRAVIS_BUILD_DIR/src/domogik/tests/travis/travis-setup-database.sh
  - $TRAVIS_BUILD_DIR/src/domogik/tests/travis/travis-install-domogik.sh
  - sudo $TRAVIS_BUILD_DIR/src/domogik/tests/travis/travis-start-domogik.sh
script:
  - $TRAVIS_BUILD_DIR/src/domogik/tests/run_test.sh
after_script:
  - $TRAVIS_BUILD_DIR/src/domogik/tests/travis/travis-after.sh
notifications:
  irc: "irc.freenode.net#domogik"
  on_success: never
  on_failure: always


